# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml --substitutions _BUCKET='<bucket name>'
steps:
- name: 'gcr.io/${PROJECT_ID}/terraform'
  dir: 'terraform'
  args:
   - 'init'
   - '-backend-config=project=${PROJECT_ID}'
   - '-backend-config=bucket=${_BUCKET}'
  env:
  - "TF_VAR_project-name=${PROJECT_ID}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  dir: 'terraform'
  args:
  - 'plan'
  env:
  - "TF_VAR_project-name=${PROJECT_ID}"
- name: 'gcr.io/${PROJECT_ID}/terraform'
  dir: 'terraform'
  args:
  - 'apply'
  - '-auto-approve'
  env:
  - "TF_VAR_project-name=${PROJECT_ID}"
- name: 'gcr.io/cloud-builders/mvn'
  dir: 'smallface/springboot'
  args:
  - 'clean'
  - 'package'
  - '-B'
  - '-DskipTests' # had to skip tests because I kept getting an error about surefire forked VM crashing
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/cloudspeed'
  - '.'
- name: 'gcr.io/${PROJECT_ID}/helm'
  args:
  - upgrade
  - --name
  - cloudspeed
  - --namespace
  - cloudspeed
  - ./helm
  - --set
  - appImage=gcr.io/$PROJECT_ID/cloudspeed
  - --install
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloudspeed-cluster'
images:
- 'gcr.io/$PROJECT_ID/cloudspeed'
substitutions:
    _BUCKET: cloud-topic-team