apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.appImage }}
        ports:
        - containerPort: {{ .Values.appPort }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://{{ .Values.postgresHost }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.postgresUsername }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.postgresPassword }}
        - name: SPRING_PROFILES_ACTIVE
          value: prod
