kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.appPort }}